sudo: required
language: cpp
services:
  - docker
before_install:
  - docker pull nandub/arch-pkgbuild
script:
  - docker run --rm -v $(pwd):/build nandub/arch-pkgbuild
branches:
  only:
    - master
